/**
 * Encode the sound pack into TypeScript modules.
 *
 * The samples live as mp3 files in client/public/audio/, but they ship as
 * base64 inside client/src/audio-pack/. Two reasons: the game then needs no
 * fetches before the first sound can play, and text survives every code
 * hosting path that mangles binary. Each sample is its own module -- one
 * file per sample keeps every file small enough for text-only transport,
 * which a single 100KB module is not. Re-run after replacing any sample:
 *
 *   npx tsx tools/encode-audio.ts
 */
import { readFileSync, readdirSync, mkdirSync, writeFileSync } from "node:fs";

const dir = new URL("../client/public/audio/", import.meta.url);
const packDir = new URL("../client/src/audio-pack/", import.meta.url);
const index = new URL("../client/src/audio-data.ts", import.meta.url);
mkdirSync(packDir, { recursive: true });

const header =
  `/**\n * GENERATED by tools/encode-audio.ts -- do not edit by hand.\n` +
  ` * The sound pack, base64-encoded so it ships as source. Regenerate with\n` +
  ` * \`npx tsx tools/encode-audio.ts\` after changing client/public/audio/.\n */\n`;

const names: string[] = [];
for (const f of readdirSync(dir).filter((f) => f.endsWith(".mp3")).sort()) {
  const name = f.replace(/\.mp3$/, "");
  const b64 = readFileSync(new URL(f, dir)).toString("base64");
  // Wrap the payload into short concatenated string literals: editors, diffs
  // and text-only transport all handle ordinary lines better than one
  // 25k-char line.
  const chunks: string[] = [];
  for (let i = 0; i < b64.length; i += 120) chunks.push(JSON.stringify(b64.slice(i, i + 120)));
  writeFileSync(
    new URL(`${name}.ts`, packDir),
    header + `export default ${chunks.join(" +\n  ")};\n`,
  );
  names.push(name);
}

writeFileSync(
  index,
  header +
    names.map((n) => `import ${n} from "./audio-pack/${n}.js";`).join("\n") +
    `\n\nexport const AUDIO_B64: Record<string, string> = {\n` +
    names.map((n) => `  ${JSON.stringify(n)}: ${n},`).join("\n") +
    `\n};\n`,
);
console.log(`encoded ${names.length} samples -> ${packDir.pathname} (+ index)`);
