/**
 * Encode the sound pack into a TypeScript module.
 *
 * The samples live as mp3 files in client/public/audio/, but they ship as
 * base64 inside client/src/audio-data.ts. Two reasons: the game then needs no
 * fetches before the first sound can play, and text survives every code
 * hosting path that mangles binary. Re-run after replacing any sample:
 *
 *   npx tsx tools/encode-audio.ts
 */
import { readFileSync, readdirSync, writeFileSync } from "node:fs";

const dir = new URL("../client/public/audio/", import.meta.url);
const out = new URL("../client/src/audio-data.ts", import.meta.url);

const entries: string[] = [];
for (const f of readdirSync(dir).filter((f) => f.endsWith(".mp3")).sort()) {
  const name = f.replace(/\.mp3$/, "");
  const b64 = readFileSync(new URL(f, dir)).toString("base64");
  // Wrap the payload into short concatenated string literals. One 25k-char
  // line is a hazard: editors, diffs and text-only transport all handle
  // ordinary lines better.
  const chunks: string[] = [];
  for (let i = 0; i < b64.length; i += 120) chunks.push(JSON.stringify(b64.slice(i, i + 120)));
  entries.push(`  ${JSON.stringify(name)}:\n    ${chunks.join(" +\n    ")},`);
}

writeFileSync(
  out,
  `/**\n * GENERATED by tools/encode-audio.ts -- do not edit by hand.\n` +
    ` * The sound pack, base64-encoded so it ships as source. Regenerate with\n` +
    ` * \`npx tsx tools/encode-audio.ts\` after changing client/public/audio/.\n */\n` +
    `export const AUDIO_B64: Record<string, string> = {\n${entries.join("\n")}\n};\n`,
);
console.log(`encoded ${entries.length} samples -> ${out.pathname}`);
