/**
 * GENERATED by tools/encode-audio.ts -- do not edit by hand.
 * The sound pack, base64-encoded so it ships as source. Regenerate with
 * `npx tsx tools/encode-audio.ts` after changing client/public/audio/.
 */
import bigexplosion from "./audio-pack/bigexplosion.js";
import build from "./audio-pack/build.js";
import cannon from "./audio-pack/cannon.js";
import click from "./audio-pack/click.js";
import explosion from "./audio-pack/explosion.js";
import harvest from "./audio-pack/harvest.js";
import rifle from "./audio-pack/rifle.js";
import rocket from "./audio-pack/rocket.js";

export const AUDIO_B64: Record<string, string> = {
  "bigexplosion": bigexplosion,
  "build": build,
  "cannon": cannon,
  "click": click,
  "explosion": explosion,
  "harvest": harvest,
  "rifle": rifle,
  "rocket": rocket,
};
