/**
 * Sound. Everything here is client-side: the sim sends no audio events, the
 * client derives them from the same snapshot diffs that drive visual effects.
 *
 * Two rules shape the design:
 *
 *  - The browser refuses audio before the first user gesture, so the
 *    AudioContext is created lazily on the first pointer/key event and every
 *    play() before that is simply dropped.
 *  - An RTS produces dozens of overlapping shots a second. Each sound has a
 *    minimum retrigger interval and a hard cap on simultaneous voices, and
 *    off-screen events are attenuated by distance and then dropped entirely
 *    past a cutoff -- without this, one tank battle is white noise.
 */
import { AUDIO_B64 } from "./audio-data.js";

function b64ToBytes(b64: string): Uint8Array {
  const bin = atob(b64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

export type SfxName =
  | "rifle"
  | "cannon"
  | "rocket"
  | "explosion"
  | "bigexplosion"
  | "build"
  | "harvest"
  | "click";

/**
 * The pack ships as base64 in audio-data.ts (generated by
 * tools/encode-audio.ts from client/public/audio/*.mp3): no fetches stand
 * between the first user gesture and the first sound.
 */
const NAMES = Object.keys(AUDIO_B64) as SfxName[];

/** Milliseconds before the same sound may start again. */
const RETRIGGER_MS: Record<SfxName, number> = {
  rifle: 90,
  cannon: 120,
  rocket: 120,
  explosion: 120,
  bigexplosion: 200,
  build: 400,
  harvest: 800,
  click: 40,
};

/** Simultaneous voices of one sound; extras are dropped, not queued. */
const MAX_VOICES: Record<SfxName, number> = {
  rifle: 6,
  cannon: 5,
  rocket: 5,
  explosion: 4,
  bigexplosion: 2,
  build: 2,
  harvest: 2,
  click: 3,
};

/** World-unit distance from the viewport centre at which a sound is silent. */
const HEARING_RANGE = 45;

export class AudioEngine {
  private ctx: AudioContext | null = null;
  private master: GainNode | null = null;
  private buffers = new Map<SfxName, AudioBuffer>();
  private lastPlay = new Map<SfxName, number>();
  private voices = new Map<SfxName, number>();
  private loading = false;

  muted = typeof localStorage !== "undefined" && localStorage.getItem("rts-muted") === "1";

  /**
   * Create/resume the context and start fetching samples. Must be called from
   * a user gesture; calling it repeatedly is cheap and safe.
   */
  unlock(): void {
    if (this.ctx) {
      if (this.ctx.state === "suspended") void this.ctx.resume();
      return;
    }
    const Ctor =
      window.AudioContext ??
      (window as unknown as { webkitAudioContext?: typeof AudioContext }).webkitAudioContext;
    if (!Ctor) return;
    this.ctx = new Ctor();
    this.master = this.ctx.createGain();
    this.master.gain.value = this.muted ? 0 : 0.8;
    this.master.connect(this.ctx.destination);
    if (!this.loading) {
      this.loading = true;
      for (const name of NAMES) {
        void this.ctx
          .decodeAudioData(b64ToBytes(AUDIO_B64[name]!).buffer as ArrayBuffer)
          .then((buf) => this.buffers.set(name, buf))
          .catch(() => {
            /* a corrupt sample just never plays */
          });
      }
    }
  }

  /** How many samples have finished decoding (tests and debugging). */
  get loadedCount(): number {
    return this.buffers.size;
  }

  toggleMute(): boolean {
    this.muted = !this.muted;
    try {
      localStorage.setItem("rts-muted", this.muted ? "1" : "0");
    } catch {
      /* private mode: mute works for the session only */
    }
    if (this.master && this.ctx) {
      this.master.gain.setValueAtTime(this.muted ? 0 : 0.8, this.ctx.currentTime);
    }
    return this.muted;
  }

  /**
   * Play a sound positioned in the world. volume falls off with distance from
   * the viewport centre; events beyond HEARING_RANGE are silent.
   */
  playAt(name: SfxName, x: number, y: number, viewCX: number, viewCY: number, volume = 1, rate = 1): void {
    const dist = Math.hypot(x - viewCX, y - viewCY);
    if (dist > HEARING_RANGE) return;
    const atten = 1 - dist / HEARING_RANGE;
    this.play(name, volume * atten * atten, rate);
  }

  /** Play a sound at a fixed volume (UI sounds, anything at the camera). */
  play(name: SfxName, volume = 1, rate = 1): void {
    if (!this.ctx || !this.master || this.muted) return;
    const buf = this.buffers.get(name);
    if (!buf) return;
    const now = performance.now();
    const last = this.lastPlay.get(name) ?? -Infinity;
    if (now - last < RETRIGGER_MS[name]) return;
    const active = this.voices.get(name) ?? 0;
    if (active >= MAX_VOICES[name]) return;
    this.lastPlay.set(name, now);
    this.voices.set(name, active + 1);

    const src = this.ctx.createBufferSource();
    src.buffer = buf;
    // Small random detune keeps repeated shots from phasing into a beat.
    src.playbackRate.value = rate * (0.94 + Math.random() * 0.12);
    const gain = this.ctx.createGain();
    gain.gain.value = Math.min(1, volume);
    src.connect(gain);
    gain.connect(this.master);
    src.onended = () => this.voices.set(name, (this.voices.get(name) ?? 1) - 1);
    src.start();
  }
}
